databases:
  -name: subgraph_implementation
   databaseName: subgraph_implementation
   user: College

services:
  -type: web
   name: College 
   runtime: python
   buildCommand: "./build.sh"
   startCommand: "gunicorn College.wsgi"
   envVars:
    -key: DATABASE_URL
      fromDatabase:
       name: College
       property: connectionString
    -key: SECRET_KEY
     generateValue: true
    -key: WEB_CONCURRENCY
     value: 4
    
