# Generated by Django 4.2 on 2023-09-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowRate', models.CharField(max_length=200)),
                ('cash', models.CharField(max_length=200)),
                ('collateralFactor', models.CharField(max_length=200)),
                ('exchangeRate', models.CharField(max_length=200)),
                ('interestRateModelAddress', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('reserves', models.CharField(max_length=200)),
                ('supplyRate', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('ids', models.CharField(default=2, max_length=200)),
                ('totalBorrows', models.CharField(max_length=200)),
                ('totalSupply', models.CharField(max_length=200)),
                ('underlyingAddress', models.CharField(max_length=200)),
                ('underlyingName', models.CharField(max_length=200)),
                ('underlyingPrice', models.CharField(max_length=200)),
                ('underlyingSymbol', models.CharField(max_length=200)),
                ('reserveFactor', models.CharField(max_length=200)),
                ('underlyingPriceUSD', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-dateCreated',),
            },
        ),
    ]
